import {
  AmericanFootballIcon,
  AustralianRulesIcon,
  BadmintonIcon,
  BalletIcon,
  BarreIcon,
  BaseballIcon,
  BasketballIcon,
  BoxingIcon,
  CanoeFlatwaterIcon,
  CanoeSlalomIcon,
  CircuitTrainingIcon,
  ClimbingIcon,
  CricketIcon,
  CrossTrainingIcon,
  CyclingIcon,
  DancingIcon,
  FencingIcon,
  FieldHockeyIcon,
  FootballIcon,
  FunctionalFitnessIcon,
  GaelicFootballIcon,
  GolfIcon,
  GymnasticsIcon,
  HandballIcon,
  HiitIcon,
  HikingIcon,
  HorseRidingIcon,
  HurlingIcon,
  IceHockeyIcon,
  JudoIcon,
  KickboxingIcon,
  KorfballIcon,
  LacrosseIcon,
  MmaIcon,
  MobilityIcon,
  MotorRacingIcon,
  MountainBikingIcon,
  NetballIcon,
  ObstacleCourseIcon,
  PaddleBoardingIcon,
  PaddleTennisIcon,
  ParkourIcon,
  PilatesIcon,
  PowerliftingIcon,
  RollerBladingIcon,
  RowingIcon,
  RugbyLeagueIcon,
  RugbyUnionIcon,
  RunningContinuousIcon,
  RunningIntervalsIcon,
  SailingIcon,
  SkateboardingIcon,
  SkiingCrossCountryIcon,
  SkiingDownhillIcon,
  SnowboardingIcon,
  SoftballIcon,
  SpeedSkatingIcon,
  SquashIcon,
  StrengthTrainingIcon,
  SurfingIcon,
  SwimmingIcon,
  TableTennisIcon,
  TennisIcon,
  TriathlonIcon,
  UltimateFrisbeeIcon,
  VolleyballIcon,
  WalkingIcon,
  WaterPoloIcon,
  WeightliftingGeneralIcon,
  WeightliftingOlympicIcon,
  WindsurfingIcon,
  WrestlingIcon,
  YogaIcon,
  OtherIcon,
} from "../components/icons/sports";
import AthleticsFieldIcon from "../components/icons/sports/AthleticsFieldIcon";
import CaddyingIcon from "../components/icons/sports/CaddyingIcon";
import CycloCrossIcon from "../components/icons/sports/CycloCrossIcon";
import ESportsIcon from "../components/icons/sports/ESportsIcon";
import GravelCyclingIcon from "../components/icons/sports/GravelCyclingIcon";
import HorseRacingIcon from "../components/icons/sports/HorseRacingIcon";
import KiteSurfingIcon from "../components/icons/sports/KiteSurfingIcon";
import MotorRacingBikeIcon from "../components/icons/sports/MotorRacingBikeIcon";
import PickleballIcon from "../components/icons/sports/PickleballIcon";
import PitCrewIcon from "../components/icons/sports/PitCrewIcon";
import SpikeballIcon from "../components/icons/sports/SpikeballIcon";
import TrailRunningIcon from "../components/icons/sports/TrailRunningIcon";
import UltraRunningIcon from "../components/icons/sports/UltraRunningIcon";

const activities = {
  ckysvfaau0006y9s7hyc97tx2: {
    id: "ckysvfaau0006y9s7hyc97tx2",
    slug: "barre",
    name: "Barre",
    icon: BarreIcon,
  },
  ckysvfaau0004y9s7r0jvp3a9: {
    id: "ckysvfaau0004y9s7r0jvp3a9",
    slug: "ballet",
    name: "Ballet",
    icon: BalletIcon,
  },
  ckysvfaat0000y9s75gq9960h: {
    id: "ckysvfaat0000y9s75gq9960h",
    slug: "american_football",
    name: "American Football",
    icon: AmericanFootballIcon,
  },
  ckysvfaau0002y9s7qnpf5914: {
    id: "ckysvfaau0002y9s7qnpf5914",
    slug: "athletics_field",
    name: "Athletics - Field",
    icon: AthleticsFieldIcon,
  },
  ckysvfaaw0016y9s7pav4dwwt: {
    id: "ckysvfaaw0016y9s7pav4dwwt",
    slug: "bouldering",
    name: "Bouldering",
    icon: ClimbingIcon,
  },
  ckysvfaaw0019y9s7x4r8heow: {
    id: "ckysvfaaw0019y9s7x4r8heow",
    slug: "canoe_flatwater",
    name: "Canoe Flatwater",
    icon: CanoeFlatwaterIcon,
  },
  ckysvfaat0001y9s7675sz3z6: {
    id: "ckysvfaat0001y9s7675sz3z6",
    slug: "badminton",
    name: "Badminton",
    icon: BadmintonIcon,
  },
  ckysvfaaw0017y9s7rsm1imo5: {
    id: "ckysvfaaw0017y9s7rsm1imo5",
    slug: "boxing",
    name: "Boxing",
    icon: BoxingIcon,
  },
  ckysvfaax0035y9s7kjnck44o: {
    id: "ckysvfaax0035y9s7kjnck44o",
    slug: "dancing",
    name: "Dancing",
    icon: DancingIcon,
  },
  ckysvfaaw0020y9s7fqn0hn0f: {
    id: "ckysvfaaw0020y9s7fqn0hn0f",
    slug: "canoe_slalom",
    name: "Canoe Slalom",
    icon: CanoeSlalomIcon,
  },
  ckysvfaaw0025y9s7kq49u78x: {
    id: "ckysvfaaw0025y9s7kq49u78x",
    slug: "cricket",
    name: "Cricket",
    icon: CricketIcon,
  },
  ckysvfaay0045y9s75pdlao76: {
    id: "ckysvfaay0045y9s75pdlao76",
    slug: "fencing",
    name: "Fencing",
    icon: FencingIcon,
  },
  ckysvfaaw0026y9s74u820e3w: {
    id: "ckysvfaaw0026y9s74u820e3w",
    slug: "cross_training",
    name: "Cross Training",
    icon: CrossTrainingIcon,
  },
  ckysvfaax0036y9s7btuhwlqh: {
    id: "ckysvfaax0036y9s7btuhwlqh",
    slug: "field_hockey",
    name: "Field Hockey",
    icon: FieldHockeyIcon,
  },
  ckysvfaax0031y9s7xa3uasmh: {
    id: "ckysvfaax0031y9s7xa3uasmh",
    slug: "cycling",
    name: "Cycling",
    icon: CyclingIcon,
  },
  ckysvfaay0056y9s7bphulw4v: {
    id: "ckysvfaay0056y9s7bphulw4v",
    slug: "golf",
    name: "Golf",
    icon: GolfIcon,
  },
  ckysvfaay0046y9s7sw14zvs2: {
    id: "ckysvfaay0046y9s7sw14zvs2",
    slug: "gymnastics",
    name: "Gymnastics",
    icon: GymnasticsIcon,
  },
  ckysvfaay0054y9s7md9eqpt2: {
    id: "ckysvfaay0054y9s7md9eqpt2",
    slug: "horse_riding",
    name: "Horse Riding",
    icon: HorseRidingIcon,
  },
  ckysvfaaz0066y9s74zqery4b: {
    id: "ckysvfaaz0066y9s74zqery4b",
    slug: "speed_skating",
    name: "Speed Skating",
    icon: SpeedSkatingIcon,
  },
  ckysvfaax0039y9s7nhbh9x52: {
    id: "ckysvfaax0039y9s7nhbh9x52",
    slug: "functional_fitness",
    name: "Functional Fitness",
    icon: FunctionalFitnessIcon,
  },
  ckysvfaay0052y9s7374904kt: {
    id: "ckysvfaay0052y9s7374904kt",
    slug: "hiit",
    name: "HIIT",
    icon: HiitIcon,
  },
  ckysvfaaz0069y9s77x7rxliy: {
    id: "ckysvfaaz0069y9s77x7rxliy",
    slug: "lacrosse",
    name: "Lacrosse",
    icon: LacrosseIcon,
  },
  ckysvfaaz0075y9s7jchemo4v: {
    id: "ckysvfaaz0075y9s7jchemo4v",
    slug: "mma",
    name: "MMA",
    icon: MmaIcon,
  },
  ckysvfaaz0068y9s7xd4s72b7: {
    id: "ckysvfaaz0068y9s7xd4s72b7",
    slug: "korfball",
    name: "Korfball",
    icon: KorfballIcon,
  },
  ckysvfaaz0067y9s7foso6e3v: {
    id: "ckysvfaaz0067y9s7foso6e3v",
    slug: "kick_boxing",
    name: "Kick Boxing",
    icon: KickboxingIcon,
  },
  ckysvfaay0047y9s7mnkqvprh: {
    id: "ckysvfaay0047y9s7mnkqvprh",
    slug: "handball",
    name: "Handball",
    icon: HandballIcon,
  },
  ckysvfaay0053y9s7cnk0ppnr: {
    id: "ckysvfaay0053y9s7cnk0ppnr",
    slug: "hiking",
    name: "Hiking",
    icon: HikingIcon,
  },
  ckysvfaay0058y9s75rrvl2nr: {
    id: "ckysvfaay0058y9s75rrvl2nr",
    slug: "judo",
    name: "Judo",
    icon: JudoIcon,
  },
  ckysvfab00082y9s7o4dxc8qg: {
    id: "ckysvfab00082y9s7o4dxc8qg",
    slug: "motor_racing",
    name: "Motor Racing",
    icon: MotorRacingIcon,
  },
  ckysvfaaz0076y9s7vs4tybwf: {
    id: "ckysvfaaz0076y9s7vs4tybwf",
    slug: "mountain_biking",
    name: "Mountain Biking",
    icon: MountainBikingIcon,
  },
  ckysvfab00084y9s70h9z64i2: {
    id: "ckysvfab00084y9s70h9z64i2",
    slug: "netball",
    name: "Netball",
    icon: NetballIcon,
  },
  ckysvfaaz0074y9s7z1zeg7ub: {
    id: "ckysvfaaz0074y9s7z1zeg7ub",
    slug: "mobility",
    name: "Mobility",
    icon: MobilityIcon,
  },
  ckysvfab00088y9s7a60irswd: {
    id: "ckysvfab00088y9s7a60irswd",
    slug: "paddle_boarding",
    name: "Paddle Boarding",
    icon: PaddleBoardingIcon,
  },
  ckysvfaaz0077y9s7923pjk42: {
    id: "ckysvfaaz0077y9s7923pjk42",
    slug: "obstacle_course_racing",
    name: "Obstacle Course Racing",
    icon: ObstacleCourseIcon,
  },
  ckysvfaay0057y9s7nu0fwh49: {
    id: "ckysvfaay0057y9s7nu0fwh49",
    slug: "ice_hockey",
    name: "Ice Hockey",
    icon: IceHockeyIcon,
  },
  ckysvfab10097y9s7ygywfeoe: {
    id: "ckysvfab10097y9s7ygywfeoe",
    slug: "rugby_league",
    name: "Rugby League",
    icon: RugbyLeagueIcon,
  },
  ckysvfab10092y9s7zql5alkq: {
    id: "ckysvfab10092y9s7zql5alkq",
    slug: "roller_blading",
    name: "Roller Blading",
    icon: RollerBladingIcon,
  },
  ckysvfab10095y9s7abep18eb: {
    id: "ckysvfab10095y9s7abep18eb",
    slug: "rowing",
    name: "Rowing",
    icon: RowingIcon,
  },
  ckysvfab10101y9s73o7sc7io: {
    id: "ckysvfab10101y9s73o7sc7io",
    slug: "running",
    name: "Running",
    icon: RunningContinuousIcon,
  },
  ckysvfab10107y9s73s5n3md0: {
    id: "ckysvfab10107y9s73s5n3md0",
    slug: "skateboarding",
    name: "Skateboarding",
    icon: SkateboardingIcon,
  },
  ckysvfab10103y9s7qbz13bkh: {
    id: "ckysvfab10103y9s7qbz13bkh",
    slug: "running_intervals",
    name: "Running - Intervals",
    icon: RunningIntervalsIcon,
  },
  ckysvfab10100y9s7nbhoe7us: {
    id: "ckysvfab10100y9s7nbhoe7us",
    slug: "rugby_union",
    name: "Rugby Union",
    icon: RugbyUnionIcon,
  },
  ckysvfab00091y9s78icx3zii: {
    id: "ckysvfab00091y9s78icx3zii",
    slug: "powerlifting",
    name: "Powerlifting",
    icon: PowerliftingIcon,
  },
  ckysvfab00090y9s7ldbxm4js: {
    id: "ckysvfab00090y9s7ldbxm4js",
    slug: "pilates",
    name: "Pilates",
    icon: PilatesIcon,
  },
  ckysvfab20117y9s7g5gk75n1: {
    id: "ckysvfab20117y9s7g5gk75n1",
    slug: "softball",
    name: "Softball",
    icon: SoftballIcon,
  },
  ckysvfab20116y9s72dcu3sgf: {
    id: "ckysvfab20116y9s72dcu3sgf",
    slug: "snowboarding",
    name: "Snowboarding",
    icon: SnowboardingIcon,
  },
  ckysvfab20126y9s7h97c2yuz: {
    id: "ckysvfab20126y9s7h97c2yuz",
    slug: "swimming",
    name: "Swimming",
    icon: SwimmingIcon,
  },
  ckysvfab20122y9s7vjm6lp3n: {
    id: "ckysvfab20122y9s7vjm6lp3n",
    slug: "surfing",
    name: "Surfing",
    icon: SurfingIcon,
  },
  ckysvfab20124y9s7dbft1vo0: {
    id: "ckysvfab20124y9s7dbft1vo0",
    slug: "strength_train",
    name: "Strength Training",
    icon: StrengthTrainingIcon,
  },
  ckysvfab20111y9s7w5hps0nd: {
    id: "ckysvfab20111y9s7w5hps0nd",
    slug: "skiing_x_country",
    name: "Skiing X Country",
    icon: SkiingCrossCountryIcon,
  },
  ckysvfab30131y9s7vvsx07by: {
    id: "ckysvfab30131y9s7vvsx07by",
    slug: "tennis",
    name: "Tennis",
    icon: TennisIcon,
  },
  ckysvfab30130y9s7ef4h0kpi: {
    id: "ckysvfab30130y9s7ef4h0kpi",
    slug: "table_tennis",
    name: "Table Tennis",
    icon: TableTennisIcon,
  },
  ckysvfab20114y9s7mcjgh7ps: {
    id: "ckysvfab20114y9s7mcjgh7ps",
    slug: "skiing_downhill",
    name: "Skiing - Downhill",
    icon: SkiingDownhillIcon,
  },
  ckysvfab30139y9s74s4id4s1: {
    id: "ckysvfab30139y9s74s4id4s1",
    slug: "walking",
    name: "Walking",
    icon: WalkingIcon,
  },
  ckysvfab30133y9s7ded2k8om: {
    id: "ckysvfab30133y9s7ded2k8om",
    slug: "ultimate_frisbee",
    name: "Ultimate Frisbee",
    icon: UltimateFrisbeeIcon,
  },
  ckysvfab30135y9s7ngwikv8q: {
    id: "ckysvfab30135y9s7ngwikv8q",
    slug: "weightlifting",
    name: "Weightlifting",
    icon: WeightliftingGeneralIcon,
  },
  ckysvfab30134y9s76rwpe9ti: {
    id: "ckysvfab30134y9s76rwpe9ti",
    slug: "triathlon",
    name: "Triathlon",
    icon: TriathlonIcon,
  },
  ckysvfab20120y9s7y97vjws9: {
    id: "ckysvfab20120y9s7y97vjws9",
    slug: "squash",
    name: "Squash",
    icon: SquashIcon,
  },
  ckysvfab30142y9s7b6231rpb: {
    id: "ckysvfab30142y9s7b6231rpb",
    slug: "volleyball",
    name: "Volleyball",
    icon: VolleyballIcon,
  },
  ckysvfab40146y9s7xhmex8h4: {
    id: "ckysvfab40146y9s7xhmex8h4",
    slug: "weightlifting_olympic",
    name: "Weightlifting Olympic",
    icon: WeightliftingOlympicIcon,
  },
  ckysvfab40150y9s7k7ouoswh: {
    id: "ckysvfab40150y9s7k7ouoswh",
    slug: "yoga",
    name: "Yoga",
    icon: YogaIcon,
  },
  ckysvfab40149y9s72s55pkpw: {
    id: "ckysvfab40149y9s72s55pkpw",
    slug: "wrestling",
    name: "Wrestling",
    icon: WrestlingIcon,
  },
  ckysvfaau0003y9s70c1jaozz: {
    id: "ckysvfaau0003y9s70c1jaozz",
    slug: "australian_rules",
    name: "Australian Rules",
    icon: AustralianRulesIcon,
  },
  ckysvfaau0007y9s7jlztylmc: {
    id: "ckysvfaau0007y9s7jlztylmc",
    slug: "basketball",
    name: "Basketball",
    icon: BasketballIcon,
  },
  ckysvfaau0005y9s7knri2gg9: {
    id: "ckysvfaau0005y9s7knri2gg9",
    slug: "baseball",
    name: "Baseball",
    icon: BaseballIcon,
  },
  ckysvfaaw0023y9s7secnlinv: {
    id: "ckysvfaaw0023y9s7secnlinv",
    slug: "climbing",
    name: "Climbing",
    icon: ClimbingIcon,
  },
  ckysvfaaw0021y9s7jpnvrods: {
    id: "ckysvfaaw0021y9s7jpnvrods",
    slug: "circuit_training",
    name: "Circuit Training",
    icon: CircuitTrainingIcon,
  },
  ckysvfaax0038y9s73bqd5siz: {
    id: "ckysvfaax0038y9s73bqd5siz",
    slug: "football",
    name: "Football",
    icon: FootballIcon,
  },
  ckysvfaay0055y9s7j84is417: {
    id: "ckysvfaay0055y9s7j84is417",
    slug: "hurling_camogie",
    name: "Hurling/Camogie",
    icon: HurlingIcon,
  },
  ckysvfaay0044y9s7qx07isfk: {
    id: "ckysvfaay0044y9s7qx07isfk",
    slug: "gaelic_football",
    name: "Gaelic Football",
    icon: GaelicFootballIcon,
  },
  ckysvfab00083y9s7ljcmaccx: {
    id: "ckysvfab00083y9s7ljcmaccx",
    slug: "padel_tennis",
    name: "Padel Tennis",
    icon: PaddleTennisIcon,
  },
  ckysvfab00089y9s7a5biljhm: {
    id: "ckysvfab00089y9s7a5biljhm",
    slug: "parkour",
    name: "Parkour",
    icon: ParkourIcon,
  },
  ckysvfab10104y9s7w0n2r3n1: {
    id: "ckysvfab10104y9s7w0n2r3n1",
    slug: "sailing",
    name: "Sailing",
    icon: SailingIcon,
  },
  ckysvfab30141y9s74aizf705: {
    id: "ckysvfab30141y9s74aizf705",
    slug: "water_polo",
    name: "Water Polo",
    icon: WaterPoloIcon,
  },
  ckysvfab40147y9s7nxutb9im: {
    id: "ckysvfab40147y9s7nxutb9im",
    slug: "windsurfing",
    name: "Windsurfing",
    icon: WindsurfingIcon,
  },
  ST7wsTOS1T0e7N4wJuh: {
    id: "ST7wsTOS1T0e7N4wJuh",
    slug: "gravel_cycling",
    name: "Gravel Cycling",
    icon: GravelCyclingIcon,
  },
  zeNnL84Vj1VYWoP31EE: {
    id: "zeNnL84Vj1VYWoP31EE",
    slug: "cyclo_cross",
    name: "Cyclo-Cross",
    icon: CycloCrossIcon,
  },
  m2tsqWm6sn2bJy7YwBC: {
    id: "m2tsqWm6sn2bJy7YwBC",
    slug: "trail_running",
    name: "Trail Running",
    icon: TrailRunningIcon,
  },
  BZAj46BwZoF4L75iuMT: {
    id: "BZAj46BwZoF4L75iuMT",
    slug: "ultra_running",
    name: "Ultra Running",
    icon: UltraRunningIcon,
  },
  x3rjKcOjItEqaV58XJMB: {
    id: "x3rjKcOjItEqaV58XJMB",
    slug: "motor_racing_bike",
    name: "Motor Racing - Bike",
    icon: MotorRacingBikeIcon,
  },
  "2Jzelhe6iyJ3GUtu3N4F": {
    id: "2Jzelhe6iyJ3GUtu3N4F",
    slug: "kite_surfing",
    name: "Kite Surfing",
    icon: KiteSurfingIcon,
  },
  iGmBRN7VC0AzbR4sjKKp: {
    id: "iGmBRN7VC0AzbR4sjKKp",
    slug: "pickleball",
    name: "Pickleball",
    icon: PickleballIcon,
  },
  C47qba7Rn4V1LWiqYy12: {
    id: "C47qba7Rn4V1LWiqYy12",
    slug: "spikeball",
    name: "Spikeball",
    icon: SpikeballIcon,
  },
  fnN5QPDhb3Ur7Bp7bXAH: {
    id: "fnN5QPDhb3Ur7Bp7bXAH",
    slug: "horse_racing",
    name: "Horse Racing",
    icon: HorseRacingIcon,
  },
  uIPjVyJlyimurTbtzYRk: {
    id: "uIPjVyJlyimurTbtzYRk",
    slug: "caddying",
    name: "Caddying",
    icon: CaddyingIcon,
  },
  ZyoM76BqIZ7AG7JgO78s: {
    id: "ZyoM76BqIZ7AG7JgO78s",
    slug: "pit_crew",
    name: "Motor Racing - Pit Crew",
    icon: PitCrewIcon,
  },
  JpUavpKVKC9FD4d9t4ls: {
    id: "JpUavpKVKC9FD4d9t4ls",
    slug: "e_sports",
    name: "E-Sports",
    icon: ESportsIcon,
  },
  clhry7xug0000x9b1f04e0kwm: {
    id: "clhry7xug0000x9b1f04e0kwm",
    slug: "other",
    name: "Other",
    icon: OtherIcon,
  },
};

export default activities;
